name: md2conf

on:
  push:
    branches: [main, master]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  md2conf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish docs to Confluence
        uses: ./
        with:
          md2conf_space: ${{ vars.MD2CONF_SPACE }}
          md2conf_parents: ${{ vars.MD2CONF_PARENTS }}
          md2conf_password: ${{ secrets.MD2CONF_PASSWORD }}
          project_prefix_url: ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}
