name: md2conf

on:
  push:
    branches: [main, master]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  md2conf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish docs to Confluence
        uses: ./
        with:
          mark_space: ${{ vars.MARK_SPACE }}
          mark_parents: ${{ vars.MARK_PARENTS }}
          mark_password: ${{ secrets.MARK_PASSWORD }}
          project_prefix_url: ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}
